Stat svc
Luz1634/java-explore-with-me pull request #1
Opened 2024-03-12 02:34 UTC by Luz1634

2024-03-12 17:59 UTC, z8q requested changes

2024-03-12 17:59 UTC, z8q commented on stats/stats-server/src/main/java/ru/practicum/stats/server/model/Event.java
> +@EqualsAndHashCode
В этих статьях описано, когда нужно переопределять hashCode и equals.
https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/
https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/

Если коротко, вот случаи:

- Newly created objects not yet associated with the database;
- Proxy and non-proxy objects associated with the same database record;
- Two proxy objects associated with the same database record;
- Objects inherited from a class where the equals() and hashCode() implementations are defined;
- Two identical objects from different sessions (obtained from different transactions).

В нашем случае нет необходимости в переопределении методов

2024-03-12 17:59 UTC, z8q commented on pom.xml
> +	<dependencies>
Нужно вынести зависимости в те модули, которые их используют.
Такой блок в родительском pom’е жёстко задаст список зависимостей для всех дочерних модулей, а в нашем случае (и в большинстве случаев) это не нужно.

В stats есть промежуточный  pom, который содержит информацию о подмодулях. В него тоже не стоит добавлять блок dependencies. Нужно именно в модули, которые их используют.

2024-03-12 17:59 UTC, z8q commented on pom.xml
> +	<dependencies>
Еще если мы будем использовать зависимости, которых нет в spring-boot-starter-parent (от которого мы наследуемся в корневом pom-е) — тогда тут, в корневом pom-е, такую зависимость можно прописать в блоке `<dependencyManagement>`, где будет указана зависимость с версией. А в pom’е самого модуля (где зависимость непосредственно используется) будет указываться dependency без версии. Этим обеспечивается центральное место для управления версиями зависимостей и соответственно порядок в проекте.

2024-03-12 17:59 UTC, z8q commented on docker-compose.yml
> +  db:
когда появится второй модуль, нужно будет переименовать)

2024-03-12 18:49 UTC, Luz1634 commented on docker-compose.yml
> +  db:
Я думал добавить все таблицы в одну базу данных, поэтому сделал просто db. Если необходимо сделать 2 разные, то переименую

2024-03-13 17:45 UTC, z8q approved these changes

2024-03-13 18:02 UTC, merged